# -*- coding: utf-8 -*-
"""행정구역 계층 데이터: 시 → 구 → 행정동(대표동).
- 숫자 분동(1동·2동·3동)은 대표 1개로 통합한다.
- tags: 동 성격 (build_regions.py 의 콘텐츠 블록 키)
- lm: 대표 랜드마크/거점 (동별 고유 문장 소재)
"""

# tags: sindosi(신도시) guDosim(구도심) daehak(대학가) terminal(터미널) ktx(KTX·철도역세권)
#       sandan(산업단지) tour(관광) coast(해안) eupmyeon(읍면외곽) biz(업무지구)
#       jugeo(주거단지) innov(혁신도시) admin(행정타운) oncheon(온천숙박)

CITIES = [
    {
        "slug": "cheonan", "name": "천안", "path": "/central-honam/cheonan/",
        "gus": [
            {"slug": "seobuk-gu", "name": "서북구", "intro": "불당·두정·성정과 천안아산역, 1호선 북부 축을 포함하는 천안의 신도심 축",
             "dongs": [
                {"slug": "buldang-dong", "name": "불당동", "tags": ["sindosi", "biz"], "lm": "천안아산역과 갤러리아 센터시티, 불당 카페거리"},
                {"slug": "baekseok-dong", "name": "백석동", "tags": ["jugeo", "sandan"], "lm": "백석산업단지와 이마트 인근 주거 단지"},
                {"slug": "dujeong-dong", "name": "두정동", "tags": ["daehak", "jugeo"], "lm": "1호선 두정역과 두정 먹자골목 상권"},
                {"slug": "seongjeong-dong", "name": "성정동", "tags": ["guDosim", "jugeo"], "lm": "성정동 이마트 상권과 주거 밀집지"},
                {"slug": "ssangyong-dong", "name": "쌍용동", "tags": ["jugeo"], "lm": "1호선 쌍용역과 이마트 쌍용점 일대 대단지 아파트"},
                {"slug": "buseong-dong", "name": "부성동", "tags": ["sindosi", "sandan"], "lm": "성성호수공원과 천안 신도시 확장 축"},
                {"slug": "seonghwan-eup", "name": "성환읍", "tags": ["eupmyeon", "ktx"], "lm": "1호선 성환역과 남서울대 인접권"},
                {"slug": "jiksan-eup", "name": "직산읍", "tags": ["eupmyeon", "sandan"], "lm": "1호선 직산역과 직산 산업단지"},
                {"slug": "seonggeo-eup", "name": "성거읍", "tags": ["eupmyeon", "sandan"], "lm": "성거 산업단지와 물류 단지"},
                {"slug": "ipjang-myeon", "name": "입장면", "tags": ["eupmyeon"], "lm": "입장 포도 산지와 북부 외곽 전원 생활권"},
             ]},
            {"slug": "dongnam-gu", "name": "동남구", "intro": "천안터미널·천안역과 대학가, 목천·병천 방면 외곽을 포함하는 원도심 축",
             "dongs": [
                {"slug": "sinbu-dong", "name": "신부동", "tags": ["terminal", "daehak"], "lm": "천안종합터미널과 신세계백화점, 대학가 상권"},
                {"slug": "bongmyeong-dong", "name": "봉명동", "tags": ["guDosim", "daehak"], "lm": "천안역 서측과 순천향대병원 인접권"},
                {"slug": "wonseong-dong", "name": "원성동", "tags": ["guDosim", "jugeo"], "lm": "원성동 주거지와 천안천 산책로"},
                {"slug": "munseong-dong", "name": "문성동", "tags": ["guDosim", "ktx"], "lm": "천안역과 명동거리 상권"},
                {"slug": "sinbang-dong", "name": "신방동", "tags": ["jugeo"], "lm": "신방통정지구 대단지 아파트"},
                {"slug": "cheongnyong-dong", "name": "청룡동", "tags": ["daehak", "jugeo"], "lm": "상명대·호서대 방면 대학가와 청수지구"},
                {"slug": "ilbong-dong", "name": "일봉동", "tags": ["jugeo"], "lm": "일봉산 둘레 주거지"},
                {"slug": "mokcheon-eup", "name": "목천읍", "tags": ["eupmyeon", "tour"], "lm": "독립기념관과 목천IC 일대"},
                {"slug": "byeongcheon-myeon", "name": "병천면", "tags": ["eupmyeon", "tour"], "lm": "아우내 병천순대거리와 유관순 열사 사적지"},
                {"slug": "pungse-myeon", "name": "풍세면", "tags": ["eupmyeon"], "lm": "풍세 산업단지와 남부 외곽 전원권"},
             ]},
        ],
    },
    {
        "slug": "daejeon", "name": "대전", "path": "/central-honam/daejeon/",
        "gus": [
            {"slug": "seo-gu", "name": "서구", "intro": "시청·정부청사가 있는 둔산 업무지구와 도안 신도시를 포함하는 대전의 중심 축",
             "dongs": [
                {"slug": "dunsan-dong", "name": "둔산동", "tags": ["biz", "jugeo"], "lm": "대전시청·정부대전청사와 갤러리아 타임월드"},
                {"slug": "tanbang-dong", "name": "탄방동", "tags": ["biz", "jugeo"], "lm": "탄방역과 둔산 업무지구 연접 상권"},
                {"slug": "wolpyeong-dong", "name": "월평동", "tags": ["jugeo"], "lm": "1호선 월평역과 갑천 변 아파트 단지"},
                {"slug": "galma-dong", "name": "갈마동", "tags": ["jugeo", "guDosim"], "lm": "갈마역과 둔산 서측 주거지"},
                {"slug": "mannyeon-dong", "name": "만년동", "tags": ["biz", "tour"], "lm": "한밭수목원·예술의전당과 엑스포 남측"},
                {"slug": "gwanjeo-dong", "name": "관저동", "tags": ["sindosi", "jugeo"], "lm": "관저지구 대단지와 건양대병원"},
                {"slug": "doan-dong", "name": "도안동", "tags": ["sindosi"], "lm": "도안신도시 신축 아파트 축"},
                {"slug": "gasuwon-dong", "name": "가수원동", "tags": ["jugeo"], "lm": "가수원네거리와 서남부 주거지"},
                {"slug": "jeongnim-dong", "name": "정림동", "tags": ["jugeo"], "lm": "정림동 아파트 단지와 갑천 변"},
                {"slug": "nae-dong", "name": "내동", "tags": ["guDosim", "jugeo"], "lm": "내동네거리 생활 상권"},
             ]},
            {"slug": "yuseong-gu", "name": "유성구", "intro": "온천 호텔과 충남대·카이스트, 대덕연구단지를 아우르는 숙박·대학·연구 축",
             "dongs": [
                {"slug": "bongmyeong-dong", "name": "봉명동", "tags": ["oncheon", "biz"], "lm": "유성온천역과 온천 호텔 상권"},
                {"slug": "gung-dong", "name": "궁동", "tags": ["daehak"], "lm": "충남대학교 정문 대학가 상권"},
                {"slug": "eoeun-dong", "name": "어은동", "tags": ["daehak", "jugeo"], "lm": "카이스트 인접 어은·궁동 원룸촌"},
                {"slug": "noeun-dong", "name": "노은동", "tags": ["sindosi", "jugeo"], "lm": "노은지구와 월드컵경기장역"},
                {"slug": "banseok-dong", "name": "반석동", "tags": ["sindosi", "jugeo"], "lm": "1호선 종점 반석역과 세종 연접 주거지"},
                {"slug": "jijok-dong", "name": "지족동", "tags": ["jugeo"], "lm": "지족역과 노은 생활권 아파트"},
                {"slug": "doryong-dong", "name": "도룡동", "tags": ["sandan", "biz"], "lm": "대덕연구단지와 대전컨벤션센터(DCC)"},
                {"slug": "jeonmin-dong", "name": "전민동", "tags": ["sandan", "jugeo"], "lm": "연구단지 배후 전민동 주거지"},
                {"slug": "gwanpyeong-dong", "name": "관평동", "tags": ["sandan", "sindosi"], "lm": "대덕테크노밸리와 관평동 상권"},
                {"slug": "guam-dong", "name": "구암동", "tags": ["terminal", "ktx"], "lm": "유성복합터미널 예정지와 구암역"},
             ]},
            {"slug": "dong-gu", "name": "동구", "intro": "대전역 KTX 거점과 복합터미널, 원도심 동측 주거지를 포함하는 관문 축",
             "dongs": [
                {"slug": "jungang-dong", "name": "중앙동", "tags": ["ktx", "guDosim"], "lm": "대전역과 소제동 카페거리"},
                {"slug": "yongjeon-dong", "name": "용전동", "tags": ["terminal", "jugeo"], "lm": "대전복합터미널과 용전동 숙박 상권"},
                {"slug": "seongnam-dong", "name": "성남동", "tags": ["guDosim", "jugeo"], "lm": "대전역 북측 성남동 주거지"},
                {"slug": "gayang-dong", "name": "가양동", "tags": ["jugeo", "daehak"], "lm": "가양동 주거지와 대전대 방면"},
                {"slug": "jayang-dong", "name": "자양동", "tags": ["daehak", "jugeo"], "lm": "우송대학교 인접 대학가"},
                {"slug": "panam-dong", "name": "판암동", "tags": ["jugeo"], "lm": "1호선 판암역 종점 주거지"},
                {"slug": "dae-dong", "name": "대동", "tags": ["guDosim"], "lm": "대동 하늘공원과 원도심 주거지"},
                {"slug": "gao-dong", "name": "가오동", "tags": ["jugeo", "sindosi"], "lm": "가오지구 아파트 단지"},
             ]},
            {"slug": "jung-gu", "name": "중구", "intro": "은행동 으능정이와 서대전역, 원도심 상권을 포함하는 대전의 옛 중심 축",
             "dongs": [
                {"slug": "eunhaeng-dong", "name": "은행동", "tags": ["guDosim", "biz"], "lm": "으능정이 스카이로드와 중앙로 상권"},
                {"slug": "daeheung-dong", "name": "대흥동", "tags": ["guDosim"], "lm": "대흥동 문화예술의 거리와 성모병원"},
                {"slug": "oryu-dong", "name": "오류동", "tags": ["ktx", "jugeo"], "lm": "서대전역과 오류동 숙박권"},
                {"slug": "taepyeong-dong", "name": "태평동", "tags": ["jugeo"], "lm": "태평동 유등천 변 아파트 단지"},
                {"slug": "munhwa-dong", "name": "문화동", "tags": ["jugeo", "daehak"], "lm": "충남대학교병원과 문화동 주거지"},
                {"slug": "yucheon-dong", "name": "유천동", "tags": ["guDosim", "jugeo"], "lm": "유천동 주거지와 버드내 상권"},
                {"slug": "sanseong-dong", "name": "산성동", "tags": ["jugeo", "eupmyeon"], "lm": "산성동 주거지와 보문산 남측"},
             ]},
            {"slug": "daedeok-gu", "name": "대덕구", "intro": "한남대와 대덕산업단지, 신탄진 철도 거점을 포함하는 북대전 축",
             "dongs": [
                {"slug": "ojeong-dong", "name": "오정동", "tags": ["daehak", "sandan"], "lm": "한남대학교와 오정동 농수산물시장"},
                {"slug": "songchon-dong", "name": "송촌동", "tags": ["jugeo"], "lm": "송촌동 선비마을 대단지"},
                {"slug": "jungni-dong", "name": "중리동", "tags": ["jugeo", "guDosim"], "lm": "중리동 생활 상권"},
                {"slug": "beop-dong", "name": "법동", "tags": ["jugeo"], "lm": "법동 아파트 단지와 중부권 산업 배후지"},
                {"slug": "birae-dong", "name": "비래동", "tags": ["jugeo"], "lm": "비래동 주거지와 계족산 입구"},
                {"slug": "sintanjin-dong", "name": "신탄진동", "tags": ["ktx", "sandan"], "lm": "신탄진역과 북대전 산업단지"},
                {"slug": "seokbong-dong", "name": "석봉동", "tags": ["jugeo", "sandan"], "lm": "신탄진 생활권 석봉동 주거지"},
                {"slug": "moksang-dong", "name": "목상동", "tags": ["sandan", "eupmyeon"], "lm": "대덕산업단지와 금강 변"},
             ]},
        ],
    },
    {
        "slug": "sejong", "name": "세종", "path": "/central-honam/sejong/",
        "gus": None,  # 자치구 없음 — 동을 시 바로 아래에 둔다
        "dongs": [
            {"slug": "naseong-dong", "name": "나성동", "tags": ["sindosi", "biz"], "lm": "나성동 어반아트리움 상업지구와 주상복합 축"},
            {"slug": "saerom-dong", "name": "새롬동", "tags": ["sindosi", "jugeo"], "lm": "새롬동 대단지 아파트와 새롬종합복지센터"},
            {"slug": "dajeong-dong", "name": "다정동", "tags": ["sindosi", "jugeo"], "lm": "다정동 가온마을 대단지"},
            {"slug": "hansol-dong", "name": "한솔동", "tags": ["sindosi", "jugeo"], "lm": "첫마을 한솔동 아파트 단지"},
            {"slug": "dodam-dong", "name": "도담동", "tags": ["sindosi", "biz"], "lm": "도램마을과 도담동 상권"},
            {"slug": "areum-dong", "name": "아름동", "tags": ["sindosi", "jugeo"], "lm": "아름동 범지기마을 주거지"},
            {"slug": "goun-dong", "name": "고운동", "tags": ["sindosi", "jugeo"], "lm": "고운동 가락마을 대단지"},
            {"slug": "jongchon-dong", "name": "종촌동", "tags": ["sindosi", "jugeo"], "lm": "종촌동 가재마을과 정부청사 북측 생활권"},
            {"slug": "eojin-dong", "name": "어진동", "tags": ["admin", "biz"], "lm": "정부세종청사와 밀마루전망대"},
            {"slug": "boram-dong", "name": "보람동", "tags": ["admin", "sindosi"], "lm": "세종시청과 보람동 호수공원 남측"},
            {"slug": "sodam-dong", "name": "소담동", "tags": ["sindosi", "jugeo"], "lm": "소담동 새샘마을과 금강 변"},
            {"slug": "daepyeong-dong", "name": "대평동", "tags": ["terminal", "sindosi"], "lm": "세종고속시외버스터미널과 대평동 상권"},
            {"slug": "bangok-dong", "name": "반곡동", "tags": ["sindosi", "jugeo"], "lm": "반곡동 수루배마을과 4생활권"},
            {"slug": "jiphyeon-dong", "name": "집현동", "tags": ["sindosi", "daehak"], "lm": "집현동 공동캠퍼스와 4-2생활권"},
            {"slug": "jochiwon-eup", "name": "조치원읍", "tags": ["guDosim", "daehak", "ktx"], "lm": "조치원역과 홍익대·고려대 세종캠퍼스"},
            {"slug": "geumnam-myeon", "name": "금남면", "tags": ["eupmyeon"], "lm": "금남면 용포리 일대와 대전 연접권"},
            {"slug": "bugang-myeon", "name": "부강면", "tags": ["eupmyeon", "ktx"], "lm": "부강역과 부강 산업단지"},
            {"slug": "jeonui-myeon", "name": "전의면", "tags": ["eupmyeon", "ktx"], "lm": "전의역과 전의 산업단지"},
            {"slug": "yeonseo-myeon", "name": "연서면", "tags": ["eupmyeon"], "lm": "연서면 고복저수지 일대"},
            {"slug": "janggun-myeon", "name": "장군면", "tags": ["eupmyeon"], "lm": "장군면 공주 연접 전원 생활권"},
        ],
    },
]

# ---------------- 호남권: 시 단위 ----------------
HONAM_CITIES = [
    {
        "slug": "gwangju", "name": "광주", "path": "/central-honam/honam/gwangju/",
        "intro": "호남 최대 도심. 상무 업무지구와 수완·첨단 신도심, 충장로 원도심이 공존한다",
        "gus": [
            {"slug": "seo-gu", "name": "서구", "intro": "상무지구 업무·숙박 축과 화정·풍암 주거지를 포함하는 광주의 중심 축",
             "dongs": [
                {"slug": "chipyeong-dong", "name": "치평동", "tags": ["biz", "oncheon"], "lm": "상무지구 김대중컨벤션센터와 광주시청"},
                {"slug": "hwajeong-dong", "name": "화정동", "tags": ["jugeo", "guDosim"], "lm": "화정동 주거지와 상무지구 연접권"},
                {"slug": "pungam-dong", "name": "풍암동", "tags": ["jugeo"], "lm": "풍암지구와 월드컵경기장"},
                {"slug": "geumho-dong", "name": "금호동", "tags": ["jugeo"], "lm": "금호지구 대단지 아파트"},
                {"slug": "ssangchon-dong", "name": "쌍촌동", "tags": ["jugeo", "daehak"], "lm": "쌍촌동 주거지와 호남대 인접"},
             ]},
            {"slug": "gwangsan-gu", "name": "광산구", "intro": "수완·첨단 신도심과 KTX 광주송정역을 포함하는 성장 축",
             "dongs": [
                {"slug": "suwan-dong", "name": "수완동", "tags": ["sindosi", "biz"], "lm": "수완지구 호수공원과 롯데아울렛 상권"},
                {"slug": "ssangam-dong", "name": "쌍암동", "tags": ["sandan", "sindosi"], "lm": "첨단지구 쌍암공원과 과학기술 산업 축"},
                {"slug": "songjeong-dong", "name": "송정동", "tags": ["ktx", "guDosim"], "lm": "KTX 광주송정역과 1913송정역시장"},
                {"slug": "hanam-dong", "name": "하남동", "tags": ["sandan", "jugeo"], "lm": "하남산업단지와 배후 주거지"},
                {"slug": "unnam-dong", "name": "운남동", "tags": ["jugeo"], "lm": "운남지구 아파트 단지"},
                {"slug": "singa-dong", "name": "신가동", "tags": ["jugeo", "sindosi"], "lm": "신가동 수완 연접 주거지"},
             ]},
            {"slug": "buk-gu", "name": "북구", "intro": "전남대 대학가와 운암·매곡 주거지를 포함하는 북측 생활 축",
             "dongs": [
                {"slug": "yongbong-dong", "name": "용봉동", "tags": ["daehak"], "lm": "전남대학교 정문 대학가 상권"},
                {"slug": "unam-dong", "name": "운암동", "tags": ["jugeo"], "lm": "운암동 대단지와 광주문화예술회관"},
                {"slug": "maegok-dong", "name": "매곡동", "tags": ["jugeo"], "lm": "매곡동 주거지와 국립광주박물관 인근"},
                {"slug": "ochi-dong", "name": "오치동", "tags": ["jugeo", "guDosim"], "lm": "오치동 생활 상권"},
                {"slug": "munheung-dong", "name": "문흥동", "tags": ["jugeo"], "lm": "문흥지구 아파트 단지"},
             ]},
            {"slug": "dong-gu", "name": "동구", "intro": "충장로·금남로 원도심과 동명동 카페거리를 포함하는 문화 중심 축",
             "dongs": [
                {"slug": "chungjang-dong", "name": "충장동", "tags": ["guDosim", "biz"], "lm": "충장로·금남로 상권과 아시아문화전당"},
                {"slug": "dongmyeong-dong", "name": "동명동", "tags": ["guDosim", "tour"], "lm": "동명동 카페거리"},
                {"slug": "gyerim-dong", "name": "계림동", "tags": ["guDosim", "jugeo"], "lm": "계림동 주거지와 광주역 남측"},
                {"slug": "hak-dong", "name": "학동", "tags": ["jugeo", "daehak"], "lm": "학동 조선대 방면과 남광주시장"},
                {"slug": "sansu-dong", "name": "산수동", "tags": ["guDosim", "jugeo"], "lm": "산수동 무등산 자락 주거지"},
             ]},
            {"slug": "nam-gu", "name": "남구", "intro": "봉선동 주거 중심과 양림동 근대문화 골목을 포함하는 남측 생활 축",
             "dongs": [
                {"slug": "bongseon-dong", "name": "봉선동", "tags": ["jugeo"], "lm": "봉선동 브랜드 아파트 축과 학원가"},
                {"slug": "juwol-dong", "name": "주월동", "tags": ["jugeo"], "lm": "주월동 주거지와 백운광장"},
                {"slug": "baegun-dong", "name": "백운동", "tags": ["guDosim", "jugeo"], "lm": "백운광장과 남구 생활 상권"},
                {"slug": "yangnim-dong", "name": "양림동", "tags": ["tour", "guDosim"], "lm": "양림동 근대문화유산 골목과 펭귄마을"},
             ]},
        ],
    },
    {
        "slug": "jeonju-si", "name": "전주", "path": "/central-honam/honam/jeonju-si/",
        "intro": "전북 핵심 도시. 한옥마을 관광과 혁신도시 업무, 도심 주거가 공존한다",
        "gus": [
            {"slug": "wansan-gu", "name": "완산구", "intro": "한옥마을과 전북도청 신시가지, 서부 주거지를 포함하는 전주의 남측 축",
             "dongs": [
                {"slug": "hyoja-dong", "name": "효자동", "tags": ["admin", "sindosi"], "lm": "전북도청과 서부신시가지 상권"},
                {"slug": "seosin-dong", "name": "서신동", "tags": ["jugeo"], "lm": "서신동 아파트 단지와 이마트 상권"},
                {"slug": "junghwasan-dong", "name": "중화산동", "tags": ["jugeo", "guDosim"], "lm": "중화산동 예수병원 일대"},
                {"slug": "pyeonghwa-dong", "name": "평화동", "tags": ["jugeo"], "lm": "평화동 아파트 단지와 꽃밭정이네거리"},
                {"slug": "samcheon-dong", "name": "삼천동", "tags": ["jugeo"], "lm": "삼천동 주거지와 막걸리골목"},
                {"slug": "pungnam-dong", "name": "풍남동", "tags": ["tour", "guDosim"], "lm": "전주한옥마을과 경기전·전동성당"},
             ]},
            {"slug": "deokjin-gu", "name": "덕진구", "intro": "전북대와 전주역, 혁신도시·에코시티를 포함하는 전주의 북측 축",
             "dongs": [
                {"slug": "deokjin-dong", "name": "덕진동", "tags": ["daehak", "tour"], "lm": "전북대학교와 덕진공원"},
                {"slug": "geumam-dong", "name": "금암동", "tags": ["daehak", "guDosim"], "lm": "전북대 구정문 대학가와 금암광장"},
                {"slug": "songcheon-dong", "name": "송천동", "tags": ["sindosi", "jugeo"], "lm": "에코시티와 송천동 상권"},
                {"slug": "inhu-dong", "name": "인후동", "tags": ["jugeo"], "lm": "인후동 아파트 단지와 아중리 상권"},
                {"slug": "ua-dong", "name": "우아동", "tags": ["ktx", "jugeo"], "lm": "전주역과 첫마중길"},
                {"slug": "manseong-dong", "name": "만성동", "tags": ["innov", "sindosi"], "lm": "전주혁신도시 법조타운과 만성지구"},
                {"slug": "yeoui-dong", "name": "여의동", "tags": ["innov", "jugeo"], "lm": "혁신도시 연접 여의동 주거지"},
             ]},
        ],
    },
    {
        "slug": "iksan-si", "name": "익산", "path": "/central-honam/honam/iksan-si/",
        "intro": "KTX 호남선·전라선이 갈라지는 전북 서부 교통 허브",
        "gus": None,
        "dongs": [
            {"slug": "yeongdeung-dong", "name": "영등동", "tags": ["jugeo", "biz"], "lm": "영등동 상권과 익산 신시가지 축"},
            {"slug": "eoyang-dong", "name": "어양동", "tags": ["jugeo", "sindosi"], "lm": "어양동 아파트 단지와 배산체육공원"},
            {"slug": "mohyeon-dong", "name": "모현동", "tags": ["jugeo"], "lm": "모현동 주거지와 배산 근린권"},
            {"slug": "busong-dong", "name": "부송동", "tags": ["jugeo", "sindosi"], "lm": "부송동 아파트 단지"},
            {"slug": "changin-dong", "name": "창인동", "tags": ["ktx", "guDosim"], "lm": "KTX 익산역과 구도심 상권"},
            {"slug": "sin-dong", "name": "신동", "tags": ["daehak"], "lm": "원광대학교 대학가"},
        ],
    },
    {
        "slug": "gunsan-si", "name": "군산", "path": "/central-honam/honam/gunsan-si/",
        "intro": "군산산단과 새만금 관문. 장기 출장 숙소 수요가 많은 서해안 산업 도시",
        "gus": None,
        "dongs": [
            {"slug": "susong-dong", "name": "수송동", "tags": ["jugeo", "biz"], "lm": "수송동 신시가지 상권"},
            {"slug": "naun-dong", "name": "나운동", "tags": ["jugeo"], "lm": "나운동 아파트 단지와 은파호수공원"},
            {"slug": "jochon-dong", "name": "조촌동", "tags": ["sindosi", "jugeo"], "lm": "디오션시티와 조촌동 신축 단지"},
            {"slug": "mijang-dong", "name": "미장동", "tags": ["sindosi", "jugeo"], "lm": "미장지구 아파트 단지"},
            {"slug": "osikdo-dong", "name": "오식도동", "tags": ["sandan"], "lm": "군산국가산업단지와 새만금 관문"},
            {"slug": "soryong-dong", "name": "소룡동", "tags": ["sandan", "coast"], "lm": "군산산단 배후 소룡동 숙소권"},
            {"slug": "gyeongam-dong", "name": "경암동", "tags": ["tour", "guDosim"], "lm": "경암동 철길마을"},
        ],
    },
    {
        "slug": "yeosu-si", "name": "여수", "path": "/central-honam/honam/yeosu-si/",
        "intro": "밤바다 관광과 여수국가산단이 공존하는 전남 동부 해안 도시",
        "gus": None,
        "dongs": [
            {"slug": "deokchung-dong", "name": "덕충동", "tags": ["ktx", "tour"], "lm": "여수엑스포역과 엑스포해양공원"},
            {"slug": "hak-dong", "name": "학동", "tags": ["biz", "jugeo"], "lm": "여수시청과 학동 행정타운"},
            {"slug": "yeoseo-dong", "name": "여서동", "tags": ["jugeo"], "lm": "여서동 주거지와 부영 아파트 축"},
            {"slug": "munsu-dong", "name": "문수동", "tags": ["jugeo"], "lm": "문수동 아파트 단지와 학원가"},
            {"slug": "ungcheon-dong", "name": "웅천동", "tags": ["sindosi", "coast"], "lm": "웅천친수공원과 신축 주거·숙박 축"},
            {"slug": "singi-dong", "name": "신기동", "tags": ["jugeo"], "lm": "신기동 주거지와 여수산단 배후권"},
            {"slug": "soho-dong", "name": "소호동", "tags": ["coast", "jugeo"], "lm": "소호동 요트장과 해안 주거지"},
            {"slug": "dolsan-eup", "name": "돌산읍", "tags": ["tour", "coast", "eupmyeon"], "lm": "돌산대교와 향일암, 펜션 밀집권"},
        ],
    },
    {
        "slug": "suncheon-si", "name": "순천", "path": "/central-honam/honam/suncheon-si/",
        "intro": "순천만 정원과 신대지구 신도심을 가진 전남 동부 생활 중심 도시",
        "gus": None,
        "dongs": [
            {"slug": "jorye-dong", "name": "조례동", "tags": ["biz", "jugeo"], "lm": "조례호수공원과 순천 신시가지 상권"},
            {"slug": "yeonhyang-dong", "name": "연향동", "tags": ["jugeo", "biz"], "lm": "연향동 상권과 팔마체육관"},
            {"slug": "wangjo-dong", "name": "왕조동", "tags": ["jugeo"], "lm": "왕조동 아파트 단지"},
            {"slug": "jogok-dong", "name": "조곡동", "tags": ["ktx", "guDosim"], "lm": "순천역과 조곡동 철도 관사마을"},
            {"slug": "pungdeok-dong", "name": "풍덕동", "tags": ["tour", "jugeo"], "lm": "순천만국가정원 인접 풍덕동"},
            {"slug": "maegok-dong", "name": "매곡동", "tags": ["jugeo", "daehak"], "lm": "매곡동 주거지와 순천대 방면"},
            {"slug": "haeryong-myeon", "name": "해룡면", "tags": ["sindosi", "eupmyeon"], "lm": "신대지구 신도심과 광양만권 배후 주거지"},
        ],
    },
    {
        "slug": "gwangyang-si", "name": "광양", "path": "/central-honam/honam/gwangyang-si/",
        "intro": "광양항과 광양제철소를 가진 산업 도시. 중마동이 생활 중심",
        "gus": None,
        "dongs": [
            {"slug": "jungma-dong", "name": "중마동", "tags": ["biz", "jugeo"], "lm": "중마동 상권과 광양시청"},
            {"slug": "gwangyang-eup", "name": "광양읍", "tags": ["guDosim", "eupmyeon"], "lm": "광양읍 구도심과 광양역"},
            {"slug": "geumho-dong", "name": "금호동", "tags": ["sandan", "jugeo"], "lm": "광양제철소 주택단지"},
            {"slug": "golyak-dong", "name": "골약동", "tags": ["sandan", "coast"], "lm": "광양항 컨테이너부두 배후권"},
            {"slug": "taein-dong", "name": "태인동", "tags": ["sandan", "coast"], "lm": "태인동 산업 배후 생활권"},
        ],
    },
    {
        "slug": "mokpo-si", "name": "목포", "path": "/central-honam/honam/mokpo-si/",
        "intro": "하당 신도심과 유달산 원도심, 남악 연접권을 가진 서남해안 거점 도시",
        "gus": None,
        "dongs": [
            {"slug": "hadang-dong", "name": "하당동", "tags": ["sindosi", "biz"], "lm": "하당 신도심 상권과 평화광장 방면"},
            {"slug": "sang-dong", "name": "상동", "tags": ["coast", "biz"], "lm": "평화광장과 하당 해안 숙박권"},
            {"slug": "ogam-dong", "name": "옥암동", "tags": ["sindosi", "jugeo"], "lm": "옥암지구와 남악 연접 주거지"},
            {"slug": "mokwon-dong", "name": "목원동", "tags": ["guDosim", "tour"], "lm": "목포역과 유달산 원도심 골목"},
            {"slug": "yongdang-dong", "name": "용당동", "tags": ["jugeo"], "lm": "용당동 주거지와 목포대교 방면"},
            {"slug": "yeonsan-dong", "name": "연산동", "tags": ["jugeo", "sandan"], "lm": "연산동 주거지와 북항 방면"},
        ],
    },
    {
        "slug": "naju-si", "name": "나주", "path": "/central-honam/honam/naju-si/",
        "intro": "빛가람혁신도시와 나주역, 영산강 원도심을 가진 광주 연접 도시",
        "gus": None,
        "dongs": [
            {"slug": "bitgaram-dong", "name": "빛가람동", "tags": ["innov", "sindosi"], "lm": "빛가람혁신도시 한전 본사와 호수공원"},
            {"slug": "songwol-dong", "name": "송월동", "tags": ["ktx", "jugeo"], "lm": "KTX 나주역과 송월동 주거지"},
            {"slug": "seongbuk-dong", "name": "성북동", "tags": ["guDosim"], "lm": "나주 원도심과 금성관 일대"},
            {"slug": "geumnam-dong", "name": "금남동", "tags": ["guDosim", "tour"], "lm": "나주곰탕거리와 향교 일대"},
            {"slug": "nampyeong-eup", "name": "남평읍", "tags": ["eupmyeon", "jugeo"], "lm": "남평읍 광주 연접 전원 주거권"},
        ],
    },
    {
        "slug": "muan-namak", "name": "무안·남악", "path": "/central-honam/honam/muan-namak/",
        "intro": "전남도청 소재 남악신도시와 무안읍을 포함하는 행정 생활권",
        "gus": None,
        "dongs": [
            {"slug": "samhyang-eup", "name": "삼향읍", "tags": ["admin", "sindosi"], "lm": "전남도청과 남악신도시"},
            {"slug": "illo-eup", "name": "일로읍", "tags": ["sindosi", "eupmyeon"], "lm": "오룡지구 신축 아파트 축"},
            {"slug": "muan-eup", "name": "무안읍", "tags": ["eupmyeon", "guDosim"], "lm": "무안읍 전통 시가지와 초당대 방면"},
        ],
    },
    {
        "slug": "jeongeup-si", "name": "정읍", "path": "/central-honam/honam/jeongeup-si/",
        "intro": "KTX 정차역과 내장산 관문을 가진 전북 서남부 거점",
        "gus": None,
        "dongs": [
            {"slug": "suseong-dong", "name": "수성동", "tags": ["biz", "jugeo"], "lm": "정읍시청과 수성동 상권"},
            {"slug": "yeonji-dong", "name": "연지동", "tags": ["ktx", "guDosim"], "lm": "KTX 정읍역 일대"},
            {"slug": "sigi-dong", "name": "시기동", "tags": ["guDosim", "jugeo"], "lm": "시기동 원도심 상권"},
            {"slug": "naejangsang-dong", "name": "내장상동", "tags": ["tour", "eupmyeon"], "lm": "내장산 관문과 관광 숙소권"},
        ],
    },
    {
        "slug": "namwon-si", "name": "남원", "path": "/central-honam/honam/namwon-si/",
        "intro": "광한루원과 지리산 관문을 가진 전북 동남부 관광 도시",
        "gus": None,
        "dongs": [
            {"slug": "dotong-dong", "name": "도통동", "tags": ["terminal", "jugeo"], "lm": "남원시외버스터미널과 도통동 상권"},
            {"slug": "jukhang-dong", "name": "죽항동", "tags": ["tour", "guDosim"], "lm": "광한루원 인접 원도심"},
            {"slug": "hyanggyo-dong", "name": "향교동", "tags": ["jugeo", "tour"], "lm": "향교동 주거지와 남원 관광단지 방면"},
        ],
    },
    {
        "slug": "gimje-si", "name": "김제", "path": "/central-honam/honam/gimje-si/",
        "intro": "호남평야 중심의 전북 서부 도시. 새만금 배후권",
        "gus": None,
        "dongs": [
            {"slug": "yochon-dong", "name": "요촌동", "tags": ["guDosim", "biz"], "lm": "김제 시내 중심 상권"},
            {"slug": "geomsan-dong", "name": "검산동", "tags": ["jugeo"], "lm": "검산동 아파트 단지와 김제시청 방면"},
            {"slug": "sinpung-dong", "name": "신풍동", "tags": ["jugeo", "ktx"], "lm": "김제역 방면 주거지"},
        ],
    },
]
